"""leds table modified

Revision ID: 6b8d34cf00c8
Revises: 03038470652c
Create Date: 2020-02-29 19:51:18.645502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8d34cf00c8'
down_revision = '03038470652c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leds_puerto'), 'leds', ['puerto'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leds_puerto'), table_name='leds')
    # ### end Alembic commands ###
