"""leds table

Revision ID: 719734943e8f
Revises: 98b43d2df150
Create Date: 2020-02-24 18:48:20.726750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719734943e8f'
down_revision = '98b43d2df150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puerto', sa.Integer(), nullable=True),
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leds')
    # ### end Alembic commands ###
