"""sensores table

Revision ID: 8324f206fd46
Revises: 719734943e8f
Create Date: 2020-02-24 19:05:20.070404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8324f206fd46'
down_revision = '719734943e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puerto', sa.Integer(), nullable=True),
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensores')
    # ### end Alembic commands ###
