"""estados_led table

Revision ID: a68a5339c52e
Revises: 8324f206fd46
Create Date: 2020-02-29 09:43:10.401388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68a5339c52e'
down_revision = '8324f206fd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_led',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('led_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['led_id'], ['leds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_led_timestamp'), 'estados_led', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estados_led_timestamp'), table_name='estados_led')
    op.drop_table('estados_led')
    # ### end Alembic commands ###
